name: githubstatus.com

on:
  workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for
  # pull requests or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  REPO: ${{ github.repository }}

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: say
        run: echo hello, ${{ env.REPO }}
      - name: now
        run: date +%Y
      - name: bye
        run: echo bye
  hello-mswin:
    runs-on: windows-2022
    steps:
      - name: ruby
        run: ruby -v
      - name: empty file
        run: type NUL> zero.txt
      - name: md5sum
        run: |
          ruby -r digest/md5 -e 'puts Digest::MD5.hexdigest("")'
          ruby -r digest/md5 -e 'puts Digest::MD5.file("zero.txt")'
          where md5sum



