name: vim_feat-norm_ruby-dynamic-330

on: workflow_dispatch

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  vim_patch:
    runs-on: ubuntu-22.04
    env:
      # ref: v9.0.2138
      REF: fda700cb04612fe2f9301a9ba820309175decabf
      CONFIG: "--disable-gui --disable-libsodium --with-features=normal"
      LOGDIR: logdir
      PATCHDIR: patch_and_test

    strategy:
      fail-fast: false
      matrix:
        patcha: ['patch-0083']
        patchb: ['patch-0456']
        patchc: ['patch-0491']
        patchd: ['patch-0561']
        patche: ['patch-0718']
       #patcha: ['', 'patch-0083']
       #patchb: ['', 'patch-0456']
       #patchc: ['', 'patch-0491']
       #patchd: ['', 'patch-0561']
       #patche: ['', 'patch-0718']
        interp: [dynamic]

    steps:
      - name: Show message.
        run: echo 'Ruby 3.3.0 released. 2023-12-25'

      - name: Prepare patchdir and logdir
        run: |
          mkdir ${{ env.PATCHDIR }}
          mkdir ${{ env.LOGDIR }}

      - name: Checkout vim
        uses: actions/checkout@v4
        with:
          repository: svardew/vim
          ref: ${{ env.REF }}
          path: ./vim

      - name: Prepare patches
        id: patches
        shell: bash {0}
        run: |
          echo '/* File: patch-NNNN'
          echo ' * ruby-3.3 remove transient_heap.'
          echo ' * 5 patches to disable each detansient block in if_ruby.c'
          echo ' */'
          touch patch-0083
          cat <<'HERE_DOCU_MENT' | sed 's/^:\ //' > patch-0083
          : --- aa/if_ruby.c	2023-12-30 07:36:56.769577142 +0900
          : +++ bb/if_ruby.c	2023-12-30 07:37:10.293757574 +0900
          : @@ -83,7 +83,7 @@
          :  #  define rb_gc_writebarrier_unprotect	rb_gc_writebarrier_unprotect_stub
          :  # endif
          :  
          : -# if RUBY_VERSION >= 26
          : +# if RUBY_VERSION >= 26 && RUBY_VERSION <= 33
          :  #  define rb_ary_detransient	rb_ary_detransient_stub
          :  # endif
          :  
          HERE_DOCU_MENT
          touch patch-0456
          cat <<'HERE_DOCU_MENT' | sed 's/^:\ //' > patch-0456
          : --- aa/if_ruby.c	2023-12-30 07:36:56.769577142 +0900
          : +++ bb/if_ruby.c	2023-12-30 07:37:10.293757574 +0900
          : @@ -456,7 +456,7 @@
          :  static VALUE (*dll_rb_ary_new) (void);
          :  static VALUE (*dll_rb_ary_new4) (long n, const VALUE *elts);
          :  static VALUE (*dll_rb_ary_push) (VALUE, VALUE);
          : -# if RUBY_VERSION >= 26
          : +# if RUBY_VERSION >= 26 && RUBY_VERSION <= 33
          :  static void (*dll_rb_ary_detransient) (VALUE);
          :  # endif
          :  # ifdef __ia64
          HERE_DOCU_MENT
          touch patch-0491
          cat <<'HERE_DOCU_MENT' | sed 's/^:\ //' > patch-0491
          : --- aa/if_ruby.c	2023-12-30 07:36:56.769577142 +0900
          : +++ bb/if_ruby.c	2023-12-30 07:37:10.293757574 +0900
          : @@ -491,7 +491,7 @@
          :  #  endif
          :  # endif
          :  
          : -# if RUBY_VERSION >= 26
          : +# if RUBY_VERSION >= 26 && RUBY_VERSION <= 33
          :  void rb_ary_detransient_stub(VALUE x);
          :  # endif
          :  
          HERE_DOCU_MENT
          touch patch-0561
          cat <<'HERE_DOCU_MENT' | sed 's/^:\ //' > patch-0561
          : --- aa/if_ruby.c	2023-12-30 07:36:56.769577142 +0900
          : +++ bb/if_ruby.c	2023-12-30 07:37:10.293757574 +0900
          : @@ -561,7 +561,7 @@
          :  }
          :  #   endif
          :  #  endif
          : -#  if RUBY_VERSION >= 26
          : +#  if RUBY_VERSION >= 26 && RUBY_VERSION <= 33
          :      void
          :  rb_ary_detransient_stub(VALUE x)
          :  {
          HERE_DOCU_MENT
          touch patch-0718
          cat <<'HERE_DOCU_MENT' | sed 's/^:\ //' > patch-0718
          : --- aa/if_ruby.c	2023-12-30 07:36:56.769577142 +0900
          : +++ bb/if_ruby.c	2023-12-30 07:37:10.293757574 +0900
          : @@ -718,7 +718,7 @@
          :      {"rb_ary_new4", (RUBY_PROC*)&dll_rb_ary_new4},
          :  # endif
          :      {"rb_ary_push", (RUBY_PROC*)&dll_rb_ary_push},
          : -# if RUBY_VERSION >= 26
          : +# if RUBY_VERSION >= 26 && RUBY_VERSION <= 33
          :      {"rb_ary_detransient", (RUBY_PROC*)&dll_rb_ary_detransient},
          :  # endif
          :      {"rb_int2big", (RUBY_PROC*)&dll_rb_int2big},
          HERE_DOCU_MENT
          echo '/* File: patch-test_ruby'
          echo ' * ruby-3.3 change NoMethodError format.'
          echo ' * this patch loose pattern in Test_ruby_Vim_buffer_get()'
          echo ' */'
          touch patch-test_ruby
          cp ./vim/src/testdir/test_ruby.vim ./test_ruby.vim.orig
          cp ./vim/src/testdir/test_ruby.vim ./test_ruby.vim.mod
          sed -i '/NoMethodError/ s,nil:NilClass,nil, ;' ./test_ruby.vim.mod
          diff -U 0 ./test_ruby.vim.orig ./test_ruby.vim.mod > patch-test_ruby
          rm ./test_ruby.vim.*
          mv patch-* ./${{ env.PATCHDIR }}

      - name: Install ruby-3.3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.3.0

      - name: Set ruby-3.3 environment
        id: rb33env
        run: |
          which ruby
          ruby -v
          sudo touch /etc/ld.so.conf.d/vim_myruby.conf
          ruby -rrbconfig -e 'puts RbConfig::CONFIG["libdir"]' | sudo tee /etc/ld.so.conf.d/vim_myruby.conf
          sudo ldconfig
          ldconfig -p | grep ruby

      - name: configure, build
        id: build
        run: |
          str='if_ruby'
          cd ./vim
          patch src/testdir/test_ruby.vim --input ../${{ env.PATCHDIR }}/patch-test_ruby
          if ${{ matrix.patcha == 'patch-0083' }}; then
            patch src/if_ruby.c --input ../${{ env.PATCHDIR }}/${{ matrix.patcha }}
            str=${str}'+'${{ matrix.patcha }}
          fi
          if ${{ matrix.patchb == 'patch-0456' }}; then
            patch src/if_ruby.c --input ../${{ env.PATCHDIR }}/${{ matrix.patchb }}
            str=${str}'+'${{ matrix.patchb }}
          fi
          if ${{ matrix.patchc == 'patch-0491' }}; then
            patch src/if_ruby.c --input ../${{ env.PATCHDIR }}/${{ matrix.patchc }}
            str=${str}'+'${{ matrix.patchc }}
          fi
          if ${{ matrix.patchd == 'patch-0561' }}; then
            patch src/if_ruby.c --input ../${{ env.PATCHDIR }}/${{ matrix.patchd }}
            str=${str}'+'${{ matrix.patchd }}
          fi
          if ${{ matrix.patche == 'patch-0718' }}; then
            patch src/if_ruby.c --input ../${{ env.PATCHDIR }}/${{ matrix.patche }}
            str=${str}'+'${{ matrix.patche }}
          fi
          ./configure ${{ env.CONFIG }} --enable-rubyinterp=${{ matrix.interp }} --with-compiledby=${str}
          make
          ./src/vim --version

      - name: test
        id: test
        run: |
          cd ./vim/src/testdir
          make test_ruby.res
          echo '/* test_*.res count. if 0, no test success'
          echo ' */'
          find . -maxdepth 1 -type f -name 'test_*.res' | wc -l
          echo '/* cat messages'
          echo ' */'
          cat messages
          fla=$(../vim --version |grep -E '^Compi'|head -n1 |sed 's:Compiled\ by\ *::')
          echo $fla > message-x
          cat messages | sed '/^\s*$/ d; /^From/ s:^:--> :' >> messages-x
          mv messages-x ../../../${{ env.LOGDIR }}/messages-${{ matrix.interp }}-${fla}
          echo "cby=${fla}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        id: upload-artifact-log
        with:
          name: messages-${{ matrix.interp }}-${{ steps.test.outputs.fla }}
          compression-level: 0
          retention-days: 1
          path: |
            ./logdir/

  patch_summary:
    # check patched +ruby and +ruby/dyn pass test_ruby.vim
    needs: vim_patch
    runs-on: ubuntu-22.04

    steps:
      - name: Download messages from artifact.
        uses: actions/download-artifact@v4
        with:
          path: ./logdir
          merge-multiple: true

      - name: Show matrix test result
        shell: bash {0}
        run: |
          cd ./logdir
          echo '### matrix test result ...'
          echo ''
          for f in messages-*
          do
            echo '===' $f '==='
            cat $f | sed '/^\s*$/ d; /^From/ s:^:--> :'
            echo ''
          done
          echo "/* expect patched +ruby and +ruby/dyn pass test_ruby.vim"
          echo " */"

# vim: set tw=2 autoindent fdm=marker :

