name: vim +ruby/dynamic

on: workflow_dispatch

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  vim_patch:
    runs-on: ubuntu-22.04
    env:
      CC: ${{ matrix.compiler }}
      GCC_VER: 13
      CLANG_VER: 17
      LEAK_CFLAGS: -DEXITFREE
      LOG_DIR: ${{ github.workspace }}/logs
      TERM: xterm
      DISPLAY: ':99'
      DEBIAN_FRONTEND: noninteractive
      # patch 9.0.2189
      REF: 7e4f62a2575e8ce9ebb842d4246288138b11dff3
      CONFIG: "--disable-gui --disable-libsodium --with-features=normal --enable-rubyinterp=dynamic"
      LOGDIR: logdir
      PATCHDIR: patch_and_test

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc]
        interp: [dynamic]
        dllenv: [ldso, envvar]

    steps:
      - name: Show message.
        run: echo 'Ruby 3.3.0 released. 2023-12-25'

      - name: Prepare patchdir and logdir
        run: |
          mkdir ${{ env.PATCHDIR }}
          mkdir ${{ env.LOGDIR }}

      - name: Checkout vim
        uses: actions/checkout@v4
        with:
          repository: svardew/vim
          ref: ${{ env.REF }}
          path: ./vim

      - name: Prepare patches
        id: patches
        shell: bash {0}
        run: |
          echo '/* File: patch-if_ruby'
          echo ' * ruby-3.3 remove transient_heap.'
          echo ' * this patch disable rb_ary_detransient block in if_ruby.c'
          echo ' */'
          # patch-if_ruby {{{
          touch patch-if_ruby
          cat <<'HERE_DOCU_MENT' | sed 's/^:\ //' > patch-if_ruby
          : --- aa/if_ruby.c
          : +++ bb/if_ruby.c
          : @@ -86 +86 @@
          : -# if RUBY_VERSION >= 26
          : +# if RUBY_VERSION >= 26 && RUBY_VERSION <= 32
          : @@ -459 +459 @@
          : -# if RUBY_VERSION >= 26
          : +# if RUBY_VERSION >= 26 && RUBY_VERSION <= 32
          : @@ -494 +494 @@
          : -# if RUBY_VERSION >= 26
          : +# if RUBY_VERSION >= 26 && RUBY_VERSION <= 32
          : @@ -564 +564 @@
          : -#  if RUBY_VERSION >= 26
          : +#  if RUBY_VERSION >= 26 && RUBY_VERSION <= 32
          : @@ -721 +721 @@
          : -# if RUBY_VERSION >= 26
          : +# if RUBY_VERSION >= 26 && RUBY_VERSION <= 32
          HERE_DOCU_MENT
          # }}}
          echo '/* File: patch-test_ruby'
          echo ' * ruby-3.3 change NoMethodError format.'
          echo ' * this patch loose pattern in Test_ruby_Vim_buffer_get()'
          echo ' */'
          #patch-test_ruby #{{{
          touch patch-test_ruby
          cp ./vim/src/testdir/test_ruby.vim ./test_ruby.vim.orig
          cp ./vim/src/testdir/test_ruby.vim ./test_ruby.vim.mod
          sed -i '/NoMethodError/ s,nil:NilClass,nil, ;' ./test_ruby.vim.mod
          diff -U 0 ./test_ruby.vim.orig ./test_ruby.vim.mod > patch-test_ruby
          rm ./test_ruby.vim.*
          # }}}
          mv patch-* ./${{ env.PATCHDIR }}

      - name: Install ruby-3.3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.3.0

      - name: Set ruby-3.3 environment
        id: rb33env
        shell: bash {0}
        run: |
          which ruby
          ruby -v
          rubylibdir=$(ruby -rrbconfig -e 'puts RbConfig::CONFIG["libdir"]')
          if ${{ matrix.dllenv == 'ldso' }}; then
            sudo touch /etc/ld.so.conf.d/vim_myruby.conf
            echo $rubylibdir | sudo tee /etc/ld.so.conf.d/vim_myruby.conf
            sudo ldconfig
            ldconfig -p | grep ruby
            echo "/* expect, config-build-test steps refer /etc/ld.so.cache"
            echo " * for libruby.so.3.3 ..."
            echo " */"
          fi
          if ${{ matrix.dllenv == 'envvar' }}; then
            echo "rb33ldlibrarypath=${rubylibdir}"  >> $GITHUB_OUTPUT
            echo "rb33pkgconfigpath=${rubylibdir}/pkgconfig" >> $GHITHUB_OUTPUT
            echo "/* expect, each steps export LD_LIBRARY_PATH first, then make,test, etc..."
            echo " * set values from steps.rb33env.outputs.NAME"
            echo " */"
          fi

      - name: patch, configure
        run: |
          if ${{ matrix.dllenv == 'envvar' }}; then
            export LD_LIBRARY_PATH=${{ steps.rb33env.outputs.rb33ldlibrarypath }}
            export PKG_CONFIG_PATH=${{ steps.rb33env.outputs.rb33pkgconfigpath }}
          fi
          str='if_ruby_withdll-'${{ matrix.dllenv }}
          cd ./vim
          patch src/testdir/test_ruby.vim --input ../${{ env.PATCHDIR }}/patch-test_ruby
          patch src/if_ruby.c --input ../${{ env.PATCHDIR }}/patch-if_ruby
          ./configure ${{ env.CONFIG }}  --with-compiledby=${str}

      - name: modify configure warnings
        if: true
        run: |
          cd ./vim
          /bin/true
          # Append various warning flags to CFLAGS.
          sed -i -f ci/config.mk.sed ${SRCDIR}/auto/config.mk
          sed -i -f ci/config.mk.${CC}.sed ${SRCDIR}/auto/config.mk

      - name: build
        run: |
          cd vim
          make
          ./src/vim --version

      - name: test
        id: test
        shell: bash {0}
        run: |
          if ${{ matrix.dllenv == 'envvar' }}; then
            export LD_LIBRARY_PATH=${{ steps.rb33env.outputs.rb33ldlibrarypath }}
            export PKG_CONFIG_PATH=${{ steps.rb33env.outputs.rb33pkgconfigpath }}
          fi
          cd ./vim/src/testdir
          make test_ruby.res
          echo '/* test_*.res count.'
          echo ' */'
          find . -maxdepth 1 -type f -name 'test_*.res' | wc -l
          echo '/* cat messages. FAILDE or SKIPPED should not appear'
          echo ' */'
          cat messages
          fla=$(../vim --version |grep -E '^Compi'|head -n1 |sed 's:Compiled\ by\ *::')
          echo $fla > message-x
          cat messages | sed '/^\s*$/ d; /^From/ s:^:--> :' >> messages-x
          mv messages-x ../../../${{ env.LOGDIR }}/messages-${{ matrix.interp }}-${fla}
          echo "fla=${fla}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        id: upload-artifact-log
        with:
          name: messages-${{ matrix.interp }}-${{ steps.test.outputs.fla }}
          compression-level: 0
          retention-days: 1
          path: |
            ./logdir/

  patch_summary:
    # check patched +ruby and +ruby/dyn pass test_ruby.vim
    needs: vim_patch
    runs-on: ubuntu-22.04

    steps:
      - name: Download messages from artifact.
        uses: actions/download-artifact@v4
        with:
          path: ./logdir
          merge-multiple: true

      - name: Show matrix test result
        shell: bash {0}
        run: |
          cd ./logdir
          echo '### matrix test result ...'
          echo ''
          for f in messages-*
          do
            echo '===' $f '==='
            cat $f | sed '/^\s*$/ d; /^From/ s:^:--> :'
            echo ''
          done
          echo "/* expect patched +ruby and +ruby/dyn pass test_ruby.vim"
          echo " */"

# vim: set tw=2 autoindent fdm=marker :

