# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  hashfiles-ubu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      LUA_VER: 5.4

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: edit list
      run: |
        touch urls.txt
        echo 5.2.55 >> urls.txt
        echo https://123.example.jp/api/get/lua/${{ env.LUA_VER }}/lua.zip >> urls.txt
        echo '1.0.232' >> urls.txt
        cat urls.txt
  hashfiles-win:
    runs-on: windows-latest
    env:
      LUA_VER: 5.4
    steps:
    - name: edit list
      run: |
        type NUL > urls.txt
        echo 5.2.55>> urls.txt
        echo https://123.example.jp/api/get/lua/${{ env.LUA_VER }}/lua.zip >> urls.txt
        echo '1.0.232' >> urls.txt
        type urls.txt
    
