# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
env:
  LUA_VER: 5.2
  # LUA32_URL: https://123.example.jp/api/get/lua/${{ LUA_VER }}/lua32.zip

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hashfiles-ubu:
    runs-on: ubuntu-latest
    env:
      MEMO: noop
      GH_TOKEN: ${{ secrets.github_token }}
      REPO: ${{ github.repository }}
      LUA32_URL:  https://123.example.jp/api/get/lua/${{ env.LUA_VER }}/lua32.zip
    steps:
    - name: edit list
      # shell: bash (default)
      run: |
        touch urls.txt
        echo 5.2 >> urls.txt
        echo ${{ env.LUA32_URL }} >> urls.txt
        echo '1.0.232' >> urls.txt
        cat urls.txt
    - name: check hashFiles value
      run: echo ${{ hashFiles('urls.txt') }}

  hashfiles-win:
    runs-on: windows-latest
    env:
      MEMO: void
      GH_TOKEN: ${{ secrets.github_token }}
      REPO: ${{ github.repository }}
      LUA32_URL:  https://123.example.jp/api/get/lua/${{ env.LUA_VER }}/lua32.zip
    steps:
    - name: edit list
      # shell: pwsh (default)
      run: |
        touch urls.txt
        echo 5.2 >> urls.txt
        echo ${{ env.LUA32_URL }} >> urls.txt
        echo '1.0.232' >> urls.txt
        type urls.txt
    - name: check hashFiles value
      run: echo ${{ hashFiles('urls.txt') }}

